
import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Head from 'next/head'

import Home from '../containers/Home';
import Layout from '../components/Layout';

const App = (): React.ReactElement => (
  <BrowserRouter>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1>Welcome to React Router v6!</h1>
    {/* In a large app - spread out your route definitions across 
        multiple <Routes> elements so you can do code splitting more easily.  */}
    {/* In a smaller app, or with nested components that are closely 
        related - put all of your routes in one place like below */}
    <Routes>
      {/* Used <Outlet> in Layout as a placeholder to render its child routes
          <Outlet> will render either a <Home> or About. The best way to use
          <Outlet> is in layouts
      */}
      <Route element={<Layout />}>
        <Route path="/" element={<Home />} />
        <Route path="about" element={<>About</>} />
        <Route
          path="*"
          element={
            <main style={{ padding: "1rem" }}>
              <p>404 There is nothing here!</p>
            </main>
          }
        />
      </Route>
    </Routes>
  </BrowserRouter>
);

export default App;
